name: 编译 MobiRobot
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 自动升级项目版本
        run: |
          $project = Get-Content "MobiRobot/MobiRobot.vcxproj" -Raw
          $project = $project -replace "v100","v143"
          Set-Content "MobiRobot/MobiRobot.vcxproj" -Value $project

      - name: 编译 Release
        run: msbuild MobiRobot.sln /p:Configuration=Release /p:Platform=Win32

      - name: 上传EXE
        uses: actions/upload-artifact@v4
        with:
          name: MobiRobot_EXE
          path: Release/
