name: 编译 MobiRobot
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置编译环境
        uses: microsoft/setup-msbuild@v1.1

      - name: 开始编译EXE
        run: msbuild MobiRobot.sln /p:Configuration=Release /p:Platform=Win32

      - name: 上传编译结果
        uses: actions/upload-artifact@v4
        with:
          name: MobiRobot_EXE
          path: Release/
